#!/bin/bash

# ubicaciones del mbr de isolinux
mbrs=(/usr/lib/syslinux/bios/isohdpfx.bin /usr/lib/ISOLINUX/isohdpfx.bin /usr/lib/syslinux/isohdpfx.bin)

for mbr_ in ${mbrs[@]}; do
  test -f "${mbr_}" && mbr="${mbr_}"
done

if test -z "${mbr}"; then
  echo "No se puede encontrar el MBR para la ISO, instalá isolinux o syslinux"
  exit 1
fi

umount jail/proc
umount jail/var/cache/apt/archives
rm -v iso/casper/filesystem.squashfs jail/etc/mtab
rm -rv jail/tmp/*
cp -vf splash.png iso/isolinux/
cp -vf isolinux.cfg iso/isolinux/

if ! mksquashfs jail iso/casper/filesystem.squashfs ; then
  echo "No se pudo crear filesystem.squashfs"
  exit 1
fi

pushd iso

chroot ../jail dpkg-query -W --showformat='${Package} ${Version}\n' > casper/filesystem.manifest
cp casper/filesystem.manifest{,-desktop}
sed -i -e '/ubiquity/d' -e '/casper/d' casper/filesystem.manifest-desktop

md5sum casper/* > md5sum.txt

printf $(du -sx --block-size=1 ../jail | cut -f1) > casper/filesystem.size

xorriso -as genisoimage \
    -D -r -J -joliet-long -l -V "$1" \
    -b isolinux/isolinux.bin \
    -c isolinux/boot.cat \
    -iso-level 3 -no-emul-boot -partition_offset 16 -boot-load-size 4 -boot-info-table \
    -isohybrid-mbr "${mbr}" \
    -o ../"${1// /-}"-$(date +%Y.%m.%d).iso .

popd

exit $?
