#!/bin/bash
umount jail/proc
rm -v iso/casper/filesystem.squashfs jail/etc/mtab
rm -v jail/var/cache/apt/archives/*.deb
rm -rv jail/tmp/*
cp -vf splash.png iso/isolinux/
cp -vf isolinux.cfg iso/isolinux/

mksquashfs jail iso/casper/filesystem.squashfs || {
    echo "No se pudo crear filesystem.squashfs"
    exit 1
}

pushd iso

chroot ../jail dpkg-query -W --showformat='${Package} ${Version}\n'a > casper/filesystem.manifest
cp casper/filesystem.manifest{,-desktop}
sed -i -e '/ubiquity/d' -e '/casper/d' casper/filesystem.manifest-desktop

md5sum casper/* > md5sum.txt

printf $(du -sx --block-size=1 ../jail | cut -f1) > casper/filesystem.size

genisofs -D -r -V "$1" -cache-inodes \
         -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat \
         -no-emul-boot -boot-load-size 4 -boot-info-table \
         -o ../"${1// /-}"-$(date +%Y.%m.%d).iso .

popd

exit $?
